# Generated by Django 5.0 on 2023-12-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cric_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('fiftees', models.IntegerField()),
                ('hundreds', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('average', models.IntegerField()),
            ],
        ),
    ]
