# Generated by Django 5.0 on 2023-12-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cric_stats',
            name='photo',
            field=models.ImageField(default='/service/media/', upload_to='photos/'),
        ),
    ]
