# Generated by Django 5.0 on 2023-12-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_cric_stats_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cric_stats',
            name='video',
            field=models.FileField(default='media_main/defaut.mp4', upload_to='media_main'),
        ),
    ]
