# Generated by Django 5.0 on 2023-12-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_cric_stats_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cric_stats',
            name='average',
            field=models.FloatField(),
        ),
    ]
