# Generated by Django 5.0 on 2024-01-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_cric_stats_average'),
    ]

    operations = [
        migrations.CreateModel(
            name='calc_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=15)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
